apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: infrastructure

resources:
  - namespace-rhoadp.yaml
  - operatorgroup-rhoadp.yaml
  - subscription-rhoadp.yaml



