# Create openshift-storage namespace.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by=openshift-gitops
    openshift.io/cluster-monitoring: "true"
  name: openshift-adp
spec: {}
