apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhodf
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: infrastructure
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
  source:
    path: infrastructure/rhodf
    repoURL: 'https://github.com/tkagn/zorro'
    targetRevision: Head